//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restik
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public int RestaurantId { get; set; }
        public Nullable<int> NumberPerson { get; set; }
        public Nullable<System.DateTime> ArrivalDatetime { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
